
#Alacritty rules
windowrule =match:class Alacritty,float on
windowrule =match:class Alacritty, move 1200 -60,
windowrule =match:class Alacritty,size 400 100,

#zoom rules
windowrulev = float, class:(zoom)
windowrulev = size 1800 1010, class:(zoom)
windowrulev = center 1, class:(zoom)

#Discord rules
windowrulev = float, class:(vesktop)
windowrulev = size 1713 980, class:(vesktop)
windowrulev = center 1, class:(vesktop)
windowrulev = float, class:(discord)
windowrulev = size 1713 980, class:(discord)
windowrulev = center 1, class:(discord)
windowrulev = stayfocused,pinned:1, class:(hyprland-share-picker),title:(MainPicker)
# windowrulev2 =float, pinned:1, class:(hyprland-share-picker), title:(MainPicker)
windowrulev = nodim, class:(scrcpy)
windowrulev = nodim, class:(com.obsproject.Studio)

windowrulev = size 1000 500, title:(Save As)
#for special workspaces
# windowrule=dimaround, onworkspace:s[true]
workspace=s[true], gapsout:60,layoutopt:orientation:top
# windowrule= size 1713 980, onworkspace:s[true]
