hl.on("hyprland.start", function()
	hl.exec_cmd("kitty pulsemixer", { workspace = "special:pulsemixer" })
	hl.exec_cmd("kitty ncmpcpp", { workspace = "special:music" })
	hl.exec_cmd("ymuse", { workspace = "special:ymuse" })
	hl.exec_cmd("kitty", { workspace = "special:terminal" })
	hl.exec_cmd("emacs", { workspace = "special:emacs" })
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	hl.exec_cmd("mpd && mpd-rich-presence")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("syncthing")
end)
